"use strict";(self.webpackChunkipc144=self.webpackChunkipc144||[]).push([[3087],{3905:(e,t,n)=>{n.d(t,{Zo:()=>u,kt:()=>m});var o=n(7294);function a(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function r(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);t&&(o=o.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,o)}return n}function s(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?r(Object(n),!0).forEach((function(t){a(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):r(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function i(e,t){if(null==e)return{};var n,o,a=function(e,t){if(null==e)return{};var n,o,a={},r=Object.keys(e);for(o=0;o<r.length;o++)n=r[o],t.indexOf(n)>=0||(a[n]=e[n]);return a}(e,t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);for(o=0;o<r.length;o++)n=r[o],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(a[n]=e[n])}return a}var l=o.createContext({}),c=function(e){var t=o.useContext(l),n=t;return e&&(n="function"==typeof e?e(t):s(s({},t),e)),n},u=function(e){var t=c(e.components);return o.createElement(l.Provider,{value:t},e.children)},h="mdxType",p={inlineCode:"code",wrapper:function(e){var t=e.children;return o.createElement(o.Fragment,{},t)}},d=o.forwardRef((function(e,t){var n=e.components,a=e.mdxType,r=e.originalType,l=e.parentName,u=i(e,["components","mdxType","originalType","parentName"]),h=c(n),d=a,m=h["".concat(l,".").concat(d)]||h[d]||p[d]||r;return n?o.createElement(m,s(s({ref:t},u),{},{components:n})):o.createElement(m,s({ref:t},u))}));function m(e,t){var n=arguments,a=t&&t.mdxType;if("string"==typeof e||a){var r=n.length,s=new Array(r);s[0]=d;var i={};for(var l in t)hasOwnProperty.call(t,l)&&(i[l]=t[l]);i.originalType=e,i[h]="string"==typeof e?e:a,s[1]=i;for(var c=2;c<r;c++)s[c]=n[c];return o.createElement.apply(null,s)}return o.createElement.apply(null,n)}d.displayName="MDXCreateElement"},9614:(e,t,n)=>{n.r(t),n.d(t,{assets:()=>l,contentTitle:()=>s,default:()=>p,frontMatter:()=>r,metadata:()=>i,toc:()=>c});var o=n(7462),a=(n(7294),n(3905));n(8209);const r={id:"promises-async-await",title:"Promises & Async / Await",sidebar_position:2,description:"Promises & Async / Await"},s="Promises & Async / Await",i={unversionedId:"Handling-Asynchronous-Code/promises-async-await",id:"Handling-Asynchronous-Code/promises-async-await",title:"Promises & Async / Await",description:"Promises & Async / Await",source:"@site/docs/Handling-Asynchronous-Code/promises-async-await.md",sourceDirName:"Handling-Asynchronous-Code",slug:"/Handling-Asynchronous-Code/promises-async-await",permalink:"/Handling-Asynchronous-Code/promises-async-await",draft:!1,editUrl:"https://github.com/patrick-crawford/WebProgrammingToolsAndFrameworks/tree/master/docs/Handling-Asynchronous-Code/promises-async-await.md",tags:[],version:"current",sidebarPosition:2,frontMatter:{id:"promises-async-await",title:"Promises & Async / Await",sidebar_position:2,description:"Promises & Async / Await"},sidebar:"courseNotesSidebar",previous:{title:"Callbacks",permalink:"/Handling-Asynchronous-Code/callbacks"},next:{title:"Example Code",permalink:"/Handling-Asynchronous-Code/example-code"}},l={},c=[{value:"Callback Review",id:"callback-review",level:2},{value:"Promises",id:"promises",level:2},{value:"Resolve &amp; Then",id:"resolve--then",level:3},{value:"Adding Data",id:"adding-data",level:3},{value:"Reject &amp; Catch",id:"reject--catch",level:3},{value:"Putting it Together",id:"putting-it-together",level:3},{value:"Async &amp; Await",id:"async--await",level:2},{value:"Putting it Together (again)",id:"putting-it-together-again",level:3},{value:"Using Await",id:"using-await",level:3}],u={toc:c},h="wrapper";function p(e){let{components:t,...n}=e;return(0,a.kt)(h,(0,o.Z)({},u,n,{components:t,mdxType:"MDXLayout"}),(0,a.kt)("h1",{id:"promises--async--await"},"Promises & Async / Await"),(0,a.kt)("p",null,"As we have seen in our ",(0,a.kt)("a",{parentName:"p",href:"/Handling-Asynchronous-Code/callbacks"},'"callbacks"'),' discussion, JavaScript is "asynchronous" in nature. Code can be written to respond to events or wait for tasks to complete before executing. One way of handling such situations was to enclose our "follow up" logic in a function that may be passed to another function to be executed (typically, after some asynchronous logic has completed such as connecting to a database, or reading a file).'),(0,a.kt)("h2",{id:"callback-review"},"Callback Review"),(0,a.kt)("p",null,"As a quick review of the callback logic discussed earlier, consider the following three functions:"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-js"},"// output \"A\" after a random time between 0 & 3 seconds\nfunction outputA() {\n  let randomTime = Math.floor(Math.random() * 3000) + 1;\n\n  setTimeout(() => {\n    console.log('A');\n  }, randomTime);\n}\n\n// output \"B\" after a random time between 0 & 3 seconds\nfunction outputB() {\n  let randomTime = Math.floor(Math.random() * 3000) + 1;\n\n  setTimeout(() => {\n    console.log('B');\n  }, randomTime);\n}\n\n// output \"C\" after a random time between 0 & 3 seconds\nfunction outputC() {\n  let randomTime = Math.floor(Math.random() * 3000) + 1;\n\n  setTimeout(() => {\n    console.log('C');\n  }, randomTime);\n}\n")),(0,a.kt)("p",null,"If we were to execute them in order, ie:"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-js"},"outputA();\noutputB();\noutputC();\n")),(0,a.kt)("p",null,'we would have no idea which letter would be output to the console first ("A", "B", or "C"), since each function takes a random amount of time to complete. If however, we wanted to be absolutely sure that the output of the code is in the correct order ("A", "B", "C") regardless of how long it takes each function to execute, we must ensure that the "follow up" functions are passed as parameters to the functions with the asynchronous logic (ie: "callbacks"). This case is more complicated because we have 3 functions, however it can still be achieved using the following code:'),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-js"},"// output \"A\" after a random time between 0 & 3 seconds\nfunction outputA(firstCallback, secondCallback) {\n  let randomTime = Math.floor(Math.random() * 3000) + 1;\n\n  setTimeout(() => {\n    console.log('A');\n    firstCallback(secondCallback);\n  }, randomTime);\n}\n\n// output \"B\" after a random time between 0 & 3 seconds\nfunction outputB(lastCallback) {\n  let randomTime = Math.floor(Math.random() * 3000) + 1;\n\n  setTimeout(() => {\n    console.log('B');\n    lastCallback();\n  }, randomTime);\n}\n\n// output \"C\" after a random time between 0 & 3 seconds\nfunction outputC() {\n  let randomTime = Math.floor(Math.random() * 3000) + 1;\n\n  setTimeout(() => {\n    console.log('C');\n  }, randomTime);\n}\n\n// invoke the functions in order\n\noutputA(outputB, outputC);\n")),(0,a.kt)("p",null,"In the above code, we have ensured the correct flow of execution of the three functions by passing both follow up functions to the first function as parameters. The final function is then passed to the second function as a callback, so that it may be executed in the right order."),(0,a.kt)("p",null,'While this does indeed work to solve the intended problem (getting the output to happen in order: "A", "B" then "C"), we have created some code which is difficult to follow, maintain and scale. For example, what happens when we add an "outputD()" function? We would need to pass it as well to the outputA() function as a parameter, only to get passed down the chain until it is executed in the correct context (for example, after outputC() has completed). As you can imagine, this creates a problem in our code and leaves us asking: "is there a better way?"'),(0,a.kt)("h2",{id:"promises"},"Promises"),(0,a.kt)("h3",{id:"resolve--then"},"Resolve & Then"),(0,a.kt)("p",null,"Fortunately, JavaScript has the notion of the ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise"},'"Promise"')),' that can help us deal with this type of situation. Put simply, a promise object is used for asynchronous computations (like the situation in the example above) and represents a value which may be available now, or in the future, or never. Basically, what this means is that we can place our asynchronous code inside a promise object as a function with specific parameters ("resolve" and "reject"). When our code is complete, we invoke the ',(0,a.kt)("a",{parentName:"p",href:"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve"},'"resolve" function')," and if our code encounters an error, we can invoke the ",(0,a.kt)("a",{parentName:"p",href:"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject"},'"reject" function'),". We can handle both of these situations later with the ",(0,a.kt)("a",{parentName:"p",href:"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then"},".then()")," method or (in the case of an error that we wish to handle) the ",(0,a.kt)("a",{parentName:"p",href:"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch"},".catch()")," method. To see how this concept is implemented in practice, consider the following addition to the outputA() method from above:"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-js"},'// output "A" after a random time between 0 & 3 seconds\nfunction outputA() {\n  let randomTime = Math.floor(Math.random() * 3000) + 1;\n\n  return new Promise((resolve, reject) => {\n    // place our code inside a "Promise" function\n    setTimeout(() => {\n      console.log(\'A\');\n      resolve(); // call "resolve" because we have completed the function successfully\n    }, randomTime);\n  });\n}\n\n// call the outputA function and when it is "resolved", output a confirmation to the console\n\noutputA().then(() => {\n  console.log(\'outputA resolved!\');\n});\n')),(0,a.kt)("p",null,'Our "outputA()" function still behaves as it did before (outputs "A" to the console after a random period of time). However, our outputA() function now additionally returns a ',(0,a.kt)("strong",{parentName:"p"},"new Promise")," object that contains all of our asynchronous logic and its status. The container function for our logic always uses the two parameters mentioned above, ie: ",(0,a.kt)("strong",{parentName:"p"},"resolve")," and ",(0,a.kt)("strong",{parentName:"p"},"reject"),". By invoking the ",(0,a.kt)("strong",{parentName:"p"},"resolve"),' method we are placing the promise into the fulfilled state, meaning that the operation completed successfully and the character "A" was successfully output to the console. We can respond to this situation using the ',(0,a.kt)("a",{parentName:"p",href:"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then"},'"then"')," function on the returned promise object to execute some code ",(0,a.kt)("strong",{parentName:"p"},"after")," the asynchronous operation is complete! This gives us a mechanism to react to asynchronous functions that have completed successfully so that we can perform additional tasks."),(0,a.kt)("h3",{id:"adding-data"},"Adding Data"),(0,a.kt)("p",null,"Now that we have the promise structure in place and are able to ",(0,a.kt)("strong",{parentName:"p"},'"resolve"')," the promise when it has completed it's task and ",(0,a.kt)("strong",{parentName:"p"},'"then"'),' execute another function using the returned promise object (as above), we can begin to think about how to pass data from the asynchronous function to the "then" method. Fortunately, it only requires a little tweak to the above the above example to enable this functionality:'),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-js"},'// output "A" after a random time between 0 & 3 seconds\nfunction outputA() {\n  let randomTime = Math.floor(Math.random() * 3000) + 1;\n\n  return new Promise((resolve, reject) => {\n    // place our code inside a "Promise" function\n    setTimeout(() => {\n      console.log(\'A\');\n      resolve(\'outputA resolved!\'); // call "resolve" because we have completed the function successfully\n    }, randomTime);\n  });\n}\n\n// call the outputA function and when it is "resolved", output a confirmation to the console\n\noutputA().then((data) => {\n  console.log(data);\n});\n')),(0,a.kt)("p",null,"Notice how we are able to invoke the ",(0,a.kt)("strong",{parentName:"p"},"resolve()"),' function with a single parameter that stores some data (in this case a string with the text "outputA resolved!"). This is typically where we would place our freshly returned data from an asynchronous call to a web service / database, etc. The reason for this is that we will have access to it as the first parameter to the anonymous function declared inside the ',(0,a.kt)("strong",{parentName:"p"},".then")," method and this is the perfect place to process the data."),(0,a.kt)("h3",{id:"reject--catch"},"Reject & Catch"),(0,a.kt)("p",null,'It is not always safe to assume that our asynchronous calls will complete successfully. What if we\'re in the middle of a request and our connection is dropped or a database connection fails? To ensure that we handle this type of scenario gracefully, we can invoke the "reject" method instead of the "resolve" method and provide a reason why our asynchronous operation failed. This causes the promise to be in a "rejected" state and the ".catch" function will be invoked, where we can gracefully handle the error. The typical syntax for handling both "then" and "catch" in a promise is as follows:'),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-js"},'// output "A" after a random time between 0 & 3 seconds\nfunction outputA() {\n  let randomTime = Math.floor(Math.random() * 3000) + 1;\n\n  return new Promise((resolve, reject) => {\n    // place our code inside a "Promise" function\n    setTimeout(() => {\n      console.log(\'-\');\n      reject(\'outputA rejected!\'); // call "reject" because the function encountered an error\n    }, randomTime);\n  });\n}\n\n// call the outputA function and when it is "resolved" or "rejected, output a confirmation to the console\n\noutputA()\n  .then((data) => {\n    console.log(data);\n  })\n  .catch((reason) => {\n    console.log(reason);\n  });\n')),(0,a.kt)("blockquote",null,(0,a.kt)("p",{parentName:"blockquote"},(0,a.kt)("strong",{parentName:"p"},"NOTE"),': Calling "resolve()" or "reject()" won\'t immediately exit the promise and invoke the related ".then()" or ".catch()" callback - it simply puts the promise in a "resolved" or "rejected" state and code immediately following the statement will still run, ie:'),(0,a.kt)("pre",{parentName:"blockquote"},(0,a.kt)("code",{parentName:"pre",className:"language-js"},'// ...\nreject();\nconsole.log(\'I will still be executed\');\nresolve(); // This promise will not be "resolved", since the resolve() call came after reject()\n// this also works the other way around.  A promise has been "settled" once reject or resolve has been called\n// ...\n')),(0,a.kt)("p",{parentName:"blockquote"},'If we want to immediately exit the function and prevent further execution of the code within the promise, we can invoke the "return" statement, immediately following the "resolve()" or "reject()" call, ie:'),(0,a.kt)("pre",{parentName:"blockquote"},(0,a.kt)("code",{parentName:"pre",className:"language-js"},"// ...\nreject();\nreturn;\nconsole.log('I will not be executed');\n// ...\n"))),(0,a.kt)("h3",{id:"putting-it-together"},"Putting it Together"),(0,a.kt)("p",null,'Now that we know how the promise object and pattern can help us manage our asynchronous code, let\'s loop back to our original problem - ensuring that "A", "B" and "C" are output in the correct order when invoking the "outputA()", "outputB()" and "outputC()" functions, respectfully.'),(0,a.kt)("p",null,"To make it more interesting, we will alter our code such that each of the functions ",(0,a.kt)("strong",{parentName:"p"},"resolve")," with the value if the ",(0,a.kt)("em",{parentName:"p"},"randomTime")," is ",(0,a.kt)("em",{parentName:"p"},"even")," and ",(0,a.kt)("strong",{parentName:"p"},"reject")," with an error if ",(0,a.kt)("em",{parentName:"p"},"randomTime")," is ",(0,a.kt)("em",{parentName:"p"},"odd"),":"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-js"},"// output \"A\" after a random time between 0 & 3 seconds\nfunction outputA() {\n  let randomTime = Math.floor(Math.random() * 3000) + 1;\n\n  return new Promise((resolve, reject) => {\n    setTimeout(() => {\n      randomTime % 2 ? resolve('A') : reject('Error with outputA()');\n    }, randomTime);\n  });\n}\n\n// output \"B\" after a random time between 0 & 3 seconds\nfunction outputB() {\n  let randomTime = Math.floor(Math.random() * 3000) + 1;\n\n  return new Promise((resolve, reject) => {\n    setTimeout(() => {\n      randomTime % 2 ? resolve('B') : reject('Error with outputB()');\n    }, randomTime);\n  });\n}\n\n// output \"C\" after a random time between 0 & 3 seconds\nfunction outputC() {\n  let randomTime = Math.floor(Math.random() * 3000) + 1;\n\n  return new Promise((resolve, reject) => {\n    setTimeout(() => {\n      randomTime % 2 ? resolve('C') : reject('Error with outputC()');\n    }, randomTime);\n  });\n}\n")),(0,a.kt)("p",null,"If we wish to use the promises correctly to output the values in order ",(0,a.kt)("strong",{parentName:"p"},"and")," correctly handles errors, our code looks like the following (this is known as ",(0,a.kt)("a",{parentName:"p",href:"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#chaining"},'promise "chaining"'),"):"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-js"},'outputA()\n  .then((data) => {\n    console.log(data); // output the result of "outputA()" to the console\n    return outputB();\n  })\n  .then((data) => {\n    console.log(data); // output the result of "outputB()" to the console\n    return outputC();\n  })\n  .then((data) => {\n    console.log(data); // output the result of "outputC()" to the console\n  })\n  .catch((err) => {\n    console.log(err); // output the error to the console\n  });\n')),(0,a.kt)("p",null,'Success! We always have "A", followed by "B" and "C" in the console and the errors are correctly handled when they occur (preventing the subsequent promises from executing). We have the benefit of not having to ',(0,a.kt)("em",{parentName:"p"},"alter"),' the functions themselves at all if follow-up logic is necessary. Each function simply does its job, then reports back with the data ("resolves") if it was successful or sends the error ("rejects") it failed. This is a much more maintainable, scalable and cleaner approach to working with asynchronous code. This is why you will find that most modules mentioned in these notes are "promise-based", ie: if their logic is asynchronous, functions provided by the module will return ',(0,a.kt)("strong",{parentName:"p"},"Promise")," objects."),(0,a.kt)("p",null,"While functions that return promises are indeed the preferred way to work with asynchronous operations in JavaScript, as you can see from the above code, ",(0,a.kt)("em",{parentName:"p"},"working"),' with promises can sometimes be difficult. If we wish to chain promises (in the case above) We must ensure that for every "then()" callback function returns the correct follow up function and it can be difficult to visually walk through the code.'),(0,a.kt)("h2",{id:"async--await"},"Async & Await"),(0,a.kt)("p",null,"To help us work with promises more easily in JavaScript, ECMAScript 2016 (ES7) released ",(0,a.kt)("a",{parentName:"p",href:"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function"},"async")," & ",(0,a.kt)("a",{parentName:"p",href:"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await"},"await"),' as an alternative to using "then()" and "catch()"'),(0,a.kt)("h3",{id:"putting-it-together-again"},"Putting it Together (again)"),(0,a.kt)("p",null,'Knowing that there is an alternative to "then()" and "catch()", let\'s see how we can re-write the section of "Putting it Together" that ',(0,a.kt)("em",{parentName:"p"},"makes use of")," the promises (we will ",(0,a.kt)("em",{parentName:"p"},"not"),' alter the functions themselves) using "async" and "await". To achieve this, we must place our logic inside a function, ie "showOutput()" - the reason for this will be described below:'),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-js"},'async function showOutput() {\n  try {\n    let A = await outputA();\n    console.log(A); // output the result of "outputA()" to the console\n\n    let B = await outputB();\n    console.log(B); // output the result of "outputB()" to the console\n\n    let C = await outputC();\n    console.log(C); // output the result of "outputC()" to the console\n  } catch (err) {\n    console.log(err); // output the error for outputA(), outputB() or outputC() to the console\n  }\n}\n\nshowOutput();\n')),(0,a.kt)("p",null,"This is ",(0,a.kt)("em",{parentName:"p"},"much"),' cleaner and easier to read. By using the "await" operator, we\'re essentially saying "wait for this function\'s returned promise to resolve". Additionally, you can see that we actually get the resolved value from the promise!'),(0,a.kt)("h3",{id:"using-await"},"Using Await"),(0,a.kt)("blockquote",null,(0,a.kt)("p",{parentName:"blockquote"},'"await" pauses the execution of its surrounding async function until the promise is settled (that is, fulfilled or rejected). When execution resumes, the value of the await expression becomes that of the fulfilled promise.'),(0,a.kt)("p",{parentName:"blockquote"},"If the promise is rejected, the await expression throws the rejected value."),(0,a.kt)("p",{parentName:"blockquote"},(0,a.kt)("a",{parentName:"p",href:"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await"},"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await"))),(0,a.kt)("p",null,'Notice how the documentation mentions the "surrounding async function". This is because to actually ',(0,a.kt)("strong",{parentName:"p"},"use"),' the "await" operator, it ',(0,a.kt)("strong",{parentName:"p"},"must"),' be placed within a function marked as "async". If we fail to do this and try to use await outside of an async function, we will get an error:'),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre"},"SyntaxError: await is only valid in async functions and the top level bodies of modules\n")),(0,a.kt)("p",null,'You will also notice how the documentation mentions that if the promise is rejected, the await expression "throws the rejected value". This is why we must place our "await" logic within a "try" / "catch" block. If we fail to do so and one of the promise-based functions is actually rejected, we will get the following error (',(0,a.kt)("strong",{parentName:"p"},"NOTE:"),' this error also occurs if a ".catch()" function is missing when using then() & catch()):'),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre"},"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().\n")),(0,a.kt)("blockquote",null,(0,a.kt)("p",{parentName:"blockquote"},(0,a.kt)("strong",{parentName:"p"},"NOTE"),': When using "async" to identify a function, you are implicitly ',(0,a.kt)("strong",{parentName:"p"},"returning a Promise"),". This is because async functions ",(0,a.kt)("em",{parentName:"p"},"cannot"),' exist within the normal flow of execution (since they contain asynchronous code). If you do return a value from an "async" function, it will be the "resolved" value of the returned promise:'),(0,a.kt)("pre",{parentName:"blockquote"},(0,a.kt)("code",{parentName:"pre",className:"language-js"},"async function adder(num1, num2) {\n  return num1 + num2;\n}\n\nadder(1, 2).then((result) => console.log(result)); //3\n"))))}p.isMDXComponent=!0},8209:(e,t,n)=>{n(7294)}}]);